### ISSUE TITLE
udp stream

### ISSUE THREAD

**Issue by jason-shen** [kbalt/ezk#9]
Hi nice crate here, i have more of a question then a issue here, i see the sip signal is all in place, i don't see anything about stream, that is not been implemented right? if not is there any future plan for that

cheers

Jason

**Comment by kbalt** [comment]
Hi Jason,

currently no media/data streaming has been implemented. I'm currently working on a high level API for the SIP UserAgent. After that I do plan on working on media streaming but that will take some time.

I currently use the sip-ua crate for a SIP -> WebRTC bridge and implemented media streaming and processing using gstreamer there.

**Comment by jason-shen** [comment]
thats interesting, that would be a nice approach actually, any examples to show how this is implemented?
that would help heaps 

cheers

**Comment by kbalt** [comment]
The source of the bridge sadly is not yet openly available, so I don't have something concrete for you to look at right now. Earliest for the open source release may be in April but that's mostly out of my control.

Best I can do right now is give some pointers.

You'd have to implement the SDP negotiation by hand (which isn't too bad) and build your RTP session with an [rtpbin](https://gstreamer.freedesktop.org/documentation/rtpmanager/rtpbin.html?gi-language=c#rtpbin-page), udpsrc & udpsink, and codec pay/depayloader and encoder/decoder like shown in the rtpbin docs.

There some little details like the udpsrc and udpsink element should share a single socket because most SIP application send their RTP/RTCP traffic to the source of the received RTP/RTCP packets.

**Comment by jason-shen** [comment]
ok no problems totally understand, and cheers for the tip, and also for this cool crate

**Comment by jason-shen** [comment]
ok no problems totally understand, and cheers for the tip, and also for this cool crate

**Comment by jason-shen** [comment]
ok no problems totally understand, and cheers for the tip, and also for this cool crate
